version: "3.9"
services:
  
  martin-due-mysql:
    container_name: martin-due-mysql
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_PASSWORD: mypasswordisasecret
      MYSQL_USER: api
      MYSQL_ROOT_PASSWORD: myrootpasswordisasecret
      MYSQL_ROOT_USER: api
      MYSQL_DATABASE: petstore
    networks:
      - martin-due-app-network

networks:
  martin-due-app-network:
    driver: bridge